### ISSUE TITLE
Compass can't find any Sass files to compile.

### ISSUE THREAD

**Issue by thetutlage** [g13013/broccoli-compass#35]
This is what i get 

![screen shot 2015-01-24 at 4 02 35 pm](https://cloud.githubusercontent.com/assets/1706381/5887047/81091f44-a3e2-11e4-8836-f6b68ae2d12c.png)

**Comment by g13013** [comment]
Hi, 
I need some information please:
- broccoli-compass version?
- compass version
- Are you sure that your style files are copied into app/styles directory ? just to be sure :)

**Comment by thetutlage** [comment]
Compass version :- Compass 1.1.0.alpha.3 (Polaris)
Broccoli Compass version :- 0.2.3

And yes files are there

**Comment by g13013** [comment]
can you try with another compass version, maybe 1.0.0 ? I believe it's a compass issue expecting other parameters.

**Comment by g13013** [comment]
@thetutlage ping :)

**Comment by thetutlage** [comment]
No it is not compass issue , the same command on terminal works great.

**Comment by g13013** [comment]
Can you give me the structure of the input tree ?

**Comment by g13013** [comment]
is your problem solved ?

**Comment by g13013** [comment]
Can i know what was the problem ?

**Comment by thetutlage** [comment]
I actually switched to https://github.com/joefiorini/broccoli-ruby-sass and was not able to find the real issue. 

Tree structure is something like this

```
├─ app/
│ ├─ styles/
│ ├── app.scss/
├─ dist/
```

**Comment by g13013** [comment]
Should not the sassDir be 'app.scss' instead of `app/scss`?

**Comment by thetutlage** [comment]
it is `app/styles` and app.scss is the file not directory ?

**Comment by g13013** [comment]
ahh so it must not end with a `/` that's why i assumed it is a directory, it is strange thought, it should work correctly.

was the input tree that you submitted to broccoli-compass '.' ?

**Comment by thetutlage** [comment]
yes that's my bad .. `app.scss` is a file.

This is how my Broccoli file looks like

```
var compileSass = require('broccoli-compass');
var compassTree = compileSass('app/styles',{
     outputStyle: 'expanded',
     sassDir: 'app/styles',
     cssDir: 'dist'
 });
```

**Comment by g13013** [comment]
Ok, i see where's the problem.

all the paths you specify in the options must be relative to the input tree content

``` js
var compileSass = require('broccoli-compass');
var compassTree = compileSass('app/styles',{
     outputStyle: 'expanded',
     sassDir: '.', // relatively to the input tree this is equivalent to  app/styles
     cssDir: '.'   // this will output css files in the root dir so when merged
                   // css files will be available directly under dist
 });
```

**Comment by g13013** [comment]
I close, if it persist reopen !
