### ISSUE TITLE
Compass to broccoli-compass

### ISSUE THREAD

**Issue by dhenriet** [g13013/broccoli-compass#37]
I would like to compile scss files which contains compass helpers (spriting) with broccoli-compass. Sass compilation is actually very slow (= 12 sec). I am running on a symfony project and don't use ember. I do not really understand how to convert my Gruntfile or config.rb into broccoli-compass file.
If broccoli-compass uses compass to compile will it be as slower as a compass compilation ?
Anyone could help me ?

this is the config.rb I am using

```
line_comments = false
output_style = :compressed
project_path = 'src/Project/DPBundle/Resources'
css_dir = 'public/css'
sass_dir = 'sass'
images_dir = 'public/images'
http_path = '/'
http_images_path = '/bundles/projectdp/images/'
http_generated_images_path = '/bundles/projectdp/images/'
relative_assets = false
sourcemap = true
```

**Comment by g13013** [comment]
For the first question: yes, it will be a bit slower than running compass direcly, ~200ms in addition to compass compilation time, but since you're using Grunt, it will not be so different.

After installing [broccoli](http://broccolijs.com/), create a file named `Brocfile.js`:

``` js
var filter = require('broccoli-static-compiler');
var compileSass = require('broccoli-compass');
// create a tree and preprare the project directory
// content of projectPath will be availlable in a tomporary folder created
// by broccoli
var tree = filter('src/Project/DPBundle/Resources')

// now submit the project tmp folder tree to broccoli compass
var compassTree = compileSass(tree, {
    lineComments: false,
    outputStyle: 'compressed',
    cssDir: 'css',
    sassDir: 'sass',
    imagesDir: 'images',
    httpPath: '/',
    httpImagesPath: '/bundles/projectdp/images/',
    httpGeneratedImagesPath: '/bundles/projectdp/images/',
    relativeAssets: false,
    sourcemap: true,
    outputStyle: 'expanded'
  });
return compassTree;
```

now in terminal type

``` bash
broccoli build public # "public" is the destination folder, not that it must be empty
```

**Comment by dhenriet** [comment]
thanks a lot !

**Comment by g13013** [comment]
welcome :)
